### PR TITLE
Initial attempt at python3 support

### PR DESCRIPTION
**Pull request by dgelvin**
I've made an initial attempt at python 3 support.  
- Everything compiles and runs- it just doesn't work.
- There are almost certainly some places where I used `PyBytes` where I should have used `PyUnicode` (and vice versa).
- Perhaps the biggest issue is with the buffer.  It is currently using the [old python2 buffer interface](https://docs.python.org/2/c-api/buffer.html) that does not exist in python3.  I made a feeble attempt to use the new python3 memory buffer but it's almost certainly wrong.  
- I didn't make any effort to retain python2 support- I was just focused on getting this to work in python3. Once this is working I would be more than willing to go back and add the necessary switches so it supports python 2.7 as well.  Great resource [here](http://python3porting.com/cextensions.html) regarding that.

### CODE REVIEW

**Comment by auvipy** [comment]
@dgelvin could you rebase and restart your work on supporting python 3? I'm a new core maintainer

**Comment by dgelvin** [comment]
Unfortunately I no longer use librabbitmq and don't have the capacity to work on this any further.

**Comment by auvipy** [comment]
OK, i will take this over and tanks again for initial works :)

**Comment by alexpirine** [comment]
@dgelvin could you please share how did you replace librabbitmq?

@auvipy do you know what remains to be done to have a full Python 3 support?

**Comment by auvipy** [comment]
mainly C API need to be addressed

**Comment by azmeuk** [comment]
Any news about this PR?

**Comment by westover** [comment]
+1

**Comment by matusvalo** [comment]
I was working on Python3 support recently and I have some initial working code with python3 support. See my python3 branch:

https://github.com/matusvalo/librabbitmq/tree/python3

I am planning to create a PR but I want to review/test code more. The biggest change made is that current code is using rabbitmq-c library from ask repository (with old version of rabbitmq-c) and I have change it to the official repository and version 0.8.0. @auvipy could you have a look whether code in current form can be considered for PR?

**Comment by auvipy** [comment]
test localy and then send a pr

**Pull request closed without merging**
