### PR TITLE
Add support of Python3

### PR DESCRIPTION
**Pull request by matusvalo**
This PR is adding Python3 support to librabbitmq with backward compatibility with python 2.7. This is a fix of issue #13. Currently Python 3.3, 3.4 and 3.5 is supported. Code should work also with python 3.6 but it was not tested yet. Code was tested under linux with installed Python 3.5.1. Also integration with kombu was tested. The biggest changes in this commit:

- rabbitmq-c submodule is moved from https://github.com/ask/rabbitmq-c.git to official repository https://github.com/alanxz/rabbitmq-c and version is bumped to newest (0.8.0)
- rabbitmq-codegen submodule is removed
- support for python <= 2.6 is removed to avoid complex ifdefs to support Python3
- library six is added as a requirement
- librabbitmq is calling callback function with payload as memoryview instead of old style buffer

### CODE REVIEW

**Comment by cclauss** [comment]
@matusvalo This is great stuff and long overdue.  Last update to master was over a year ago and much has changed in that time.  Python 3.3 goes EOL this month and the first alpha of Python 3.7 are due so I agree with @auvipy point that 3.6 is more important than 3.3.  You might consider running [__futurize --stage1__](http://python-future.org/automatic_conversion.html#stage-1-safe-fixes) over this PR to see what other changes would be recommended.  I hope this move forward.

**Comment by matusvalo** [comment]
Support of python 3.3 was for free and this is set just because I haven't used features from higher versions of python (there was no need to use such features). But I have no problem removing official support of 3.3. My patch technicaly should be working on python 3.6 but I haven't test it. I will run the proposed tool against my patch and I will test my patch against python 3.6.

**Comment by matusvalo** [comment]
I have removed python 3.3 support and added python 3.6. I have tested patch under python 3.6 and it seems working also under kombu library. I have run proposed tool but it yields no changes using --stage1.

**Comment by MelchiSalins** [comment]
Looking forward to this being merged in.

**Comment by auvipy** [comment]
I have merged it in the master branch for testing purpose for now. test and report if any issue is found

**Comment by MelchiSalins** [comment]
So whats the process to get a new release cut and published to pypi?

**Pull request merged**
