### PR TITLE
Fix memory leaks from "Maybe_Unicode" (fixes #27 #125)

### LINKED ISSUE #27: Memory Leaks from 'Maybe_Unicode'
I've been looking into a memory leak by running [a static analysis tool](https://gcc-python-plugin.readthedocs.org/)  over the librabbitmq module. It looks like the way `Maybe_Unicode` is being used may leak object references.

``` c
_PYRMQ_INLINE PyObject*
Maybe_Unicode(PyObject *s)
{
    if (PyUnicode_Check(s))
        return PyUnicode_AsASCIIString(s);
    return s;
}
```

I see it called often after a call to `PyArg_ParseTuple`

The docs for `PyArg_ParseTuple` say:

> Note that any Python object references which are provided to the caller are borrowed references; do not decrement their reference count!

The docs for `PyUnicode_AsASCIIString` say:

> `PyObject* PyUnicode_AsASCIIString(PyObject *unicode)`
> Return value: New reference.

If `Maybe_Unicode` is intended to make new objects, the caller needs to be responsible for cleaning them up.
If the caller calls `Maybe_Unicode` with a borrowed reference, but gets back a new reference, it should decrement the refcount once it's done, but I haven't seen any evidence of that.

It may be cleaner to increment the refcount before calling, and decrement it when you're done, so that `Maybe_Unicode` can safely decrement the ref to a passed unicode object. e.g:

``` c
_PYRMQ_INLINE PyObject*
Maybe_Unicode(PyObject *s)
{
    if (PyUnicode_Check(s))
    {
        PyObject* ascii = PyUnicode_AsASCIIString(s);
        DECREF(s);
        s = ascii;
    }
    return s;
}
```

### PR DESCRIPTION
**Pull request by henryykt**
Attempt to fix memory leaks described in #27 and #125.

### CODE REVIEW

**Comment by thedrow** [comment]
Did you verify this patch with valgrind?

**Comment by henryykt** [comment]
> Did you verify this patch with valgrind?

Tested with the following:

    import json

    from librabbitmq import Connection, Message

    max_iters = 10000

    with Connection(
        host="localhost", port=5672, userid="guest", password="guest", virtual_host="/"
    ) as conn:
        with conn.channel() as channel:
            channel.exchange_declare(exchange="re", type="direct", auto_delete=False)

            data = json.dumps({"some_key": "some_value"})
            props = {"headers": {"some_header": "some_header_value"}}

            while max_iters > 0:
                max_iters -= 1

                message = Message(channel=channel, properties=props, body=data)
                channel.basic_publish(message, 're', routing_key='')

Output master branch:

	(venv_librabbitmq) [developer@dev librabbitmq]$ PYTHONMALLOC=malloc valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all python ./publish.py
	==26039== Memcheck, a memory error detector
	==26039== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
	==26039== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
	==26039== Command: python ./publish.py
	==26039==
	...
	==26039== LEAK SUMMARY:
	==26039==    definitely lost: 1,289,804 bytes in 29,996 blocks
	==26039==    indirectly lost: 0 bytes in 0 blocks
	==26039==      possibly lost: 641,114 bytes in 3,902 blocks
	==26039==    still reachable: 1,428,011 bytes in 14,090 blocks
	==26039==                       of which reachable via heuristic:
	==26039==                         newarray           : 60 bytes in 1 blocks
	==26039==         suppressed: 0 bytes in 0 blocks
	==26039==
	==26039== For counts of detected and suppressed errors, rerun with: -v
	==26039== ERROR SUMMARY: 717 errors from 717 contexts (suppressed: 0 from 0)

Output with fix:

	(venv_librabbitmq) [developer@dev librabbitmq]$ PYTHONMALLOC=malloc valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all python ./publish.py
	==26385== Memcheck, a memory error detector
	==26385== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
	==26385== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
	==26385== Command: python ./publish.py
	==26385==
	...
	==26385== LEAK SUMMARY:
	==26385==    definitely lost: 0 bytes in 0 blocks
	==26385==    indirectly lost: 0 bytes in 0 blocks
	==26385==      possibly lost: 640,888 bytes in 3,897 blocks
	==26385==    still reachable: 1,427,967 bytes in 14,089 blocks
	==26385==                       of which reachable via heuristic:
	==26385==                         newarray           : 60 bytes in 1 blocks
	==26385==         suppressed: 0 bytes in 0 blocks
	==26385==
	==26385== For counts of detected and suppressed errors, rerun with: -v
	==26385== ERROR SUMMARY: 710 errors from 710 contexts (suppressed: 0 from 0)

**Comment by auvipy** [comment]
can you rebase?

**Comment by henryykt** [comment]
> can you rebase?

done

**Pull request merged**
