### PR TITLE
Don't remove -Wall, since that can break compilation. Fixes #68

### LINKED ISSUE #68: pip install librabbitmq fails because of removing -Wall
Here's the pip install log. This is on Fedora 21 with gcc 4.9.2

```
$ pip install librabbitmq
Collecting librabbitmq
  Using cached librabbitmq-1.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): amqp>=1.4.6 in /home/aron/.virtualenvs/pp/lib/python2.7/site-packages (from librabbitmq)
Installing collected packages: librabbitmq
  Running setup.py install for librabbitmq
    Complete output from command /home/aron/.virtualenvs/pp/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-EmpTYQ/librabbitmq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tb1kGg-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/aron/.virtualenvs/pp/include/site/python2.7/librabbitmq:
    running build
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether make supports nested variables... (cached) yes
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/tmp/pip-build-EmpTYQ/librabbitmq/clib':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
...
```

Here is what we see in `config.log`

```
configure:3333: checking whether the C compiler works
configure:3355: gcc -fno-strict-aliasing -O2 -g -pipe  -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv  -DNDEBUG -O2 -g -pipe  -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv  -Wl,-z,relro conftest.c  >&5
cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]
```

I found that this can be avoided by dropping the line in `setup.py` that removes `-Wall` from the command-line.

### PR DESCRIPTION
**Pull request by agriffis**

### CODE REVIEW

**Comment by agriffis** [comment]
This doesn't completely fix pip install on Fedora. I just run into build errors after that:
```
Obtaining librabbitmq from git+git://github.com/agriffis/librabbitmq@2bf03190b573b33b78a20da382aaa64816176fc0#egg=librabbitmq-dev
  Updating /home/aron/.virtualenvs/pp/src/librabbitmq clone (to 2bf03190b573b33b78a20da382aaa64816176fc0)
  Could not find a tag or branch '2bf03190b573b33b78a20da382aaa64816176fc0', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): amqp>=1.4.6 in /home/aron/.virtualenvs/pp/lib/python2.7/site-packages (from librabbitmq)
Installing collected packages: librabbitmq
  Running setup.py develop for librabbitmq
    Complete output from command /home/aron/.virtualenvs/pp/bin/python2 -c "import setuptools, tokenize; __file__='/home/aron/.virtualenvs/pp/src/librabbitmq/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to librabbitmq.egg-info/requires.txt
    writing librabbitmq.egg-info/PKG-INFO
    writing top-level names to librabbitmq.egg-info/top_level.txt
    writing dependency_links to librabbitmq.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'librabbitmq.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'tests'
    warning: no files found matching '*' under directory 'clib'
    no previously-included directories found matching '*.pyc'
    no previously-included directories found matching '*.o'
    no previously-included directories found matching '*.la'
    no previously-included directories found matching '*.so'
    no previously-included directories found matching '*.dylib'
    writing manifest file 'librabbitmq.egg-info/SOURCES.txt'
    running build_ext
    building '_librabbitmq' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iclib/librabbitmq -Iclib -I/usr/include/python2.7 -c Modules/_librabbitmq/connection.c -o build/temp.linux-x86_64-2.7/Modules/_librabbitmq/connection.o
    In file included from /usr/include/python2.7/pyconfig.h:6:0,
                     from /usr/include/python2.7/Python.h:8,
                     from Modules/_librabbitmq/connection.h:4,
                     from Modules/_librabbitmq/connection.c:11:
    /usr/include/python2.7/pyconfig-64.h:1191:0: warning: "_POSIX_C_SOURCE" redefined
     #define _POSIX_C_SOURCE 200112L
     ^
    In file included from /usr/include/stdlib.h:24:0,
                     from Modules/_librabbitmq/connection.c:1:
    /usr/include/features.h:225:0: note: this is the location of the previous definition
     # define _POSIX_C_SOURCE 200809L
     ^
    In file included from /usr/include/python2.7/pyconfig.h:6:0,
                     from /usr/include/python2.7/Python.h:8,
                     from Modules/_librabbitmq/connection.h:4,
                     from Modules/_librabbitmq/connection.c:11:
    /usr/include/python2.7/pyconfig-64.h:1213:0: warning: "_XOPEN_SOURCE" redefined
     #define _XOPEN_SOURCE 600
     ^
    In file included from /usr/include/stdlib.h:24:0,
                     from Modules/_librabbitmq/connection.c:1:
    /usr/include/features.h:166:0: note: this is the location of the previous definition
     # define _XOPEN_SOURCE 700
     ^
    Modules/_librabbitmq/connection.c: In function ‘PyIter_ToAMQArray’:
    Modules/_librabbitmq/connection.c:335:5: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
         while (item = PyIter_Next(iterator)) {
         ^
    Modules/_librabbitmq/connection.c:380:1: warning: label ‘error’ defined but not used [-Wunused-label]
     error:
     ^
    Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_close’:
    Modules/_librabbitmq/connection.c:1043:22: warning: variable ‘reply’ set but not used [-Wunused-but-set-variable]
         amqp_rpc_reply_t reply;
                          ^
    Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_exchange_declare’:
    Modules/_librabbitmq/connection.c:1672:5: error: incompatible type for argument 7 of ‘amqp_exchange_declare’
         amqp_exchange_declare(self->conn, channel,
         ^
    In file included from /usr/include/amqp.h:732:0,
                     from Modules/_librabbitmq/connection.c:8:
    /usr/include/amqp_framing.h:620:71: note: expected ‘amqp_table_t’ but argument is of type ‘int’
     AMQP_PUBLIC_FUNCTION amqp_exchange_declare_ok_t * AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_bytes_t type, amqp_boolean_t passive, amqp_boolean_t durable, amqp_table_t arguments);
                                                                           ^
    Modules/_librabbitmq/connection.c:1672:5: error: too many arguments to function ‘amqp_exchange_declare’
         amqp_exchange_declare(self->conn, channel,
         ^
    In file included from /usr/include/amqp.h:732:0,
                     from Modules/_librabbitmq/connection.c:8:
    /usr/include/amqp_framing.h:620:71: note: declared here
     AMQP_PUBLIC_FUNCTION amqp_exchange_declare_ok_t * AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_bytes_t type, amqp_boolean_t passive, amqp_boolean_t durable, amqp_table_t arguments);
                                                                           ^
    Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_basic_cancel’:
    Modules/_librabbitmq/connection.c:1870:29: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
         amqp_basic_cancel_ok_t *ok;
                                 ^
    Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_flow’:
    Modules/_librabbitmq/connection.c:1995:29: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
         amqp_channel_flow_ok_t *ok;
                                 ^
    Modules/_librabbitmq/connection.c: In function ‘PyRabbitMQ_Connection_basic_recover’:
    Modules/_librabbitmq/connection.c:2028:30: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
         amqp_basic_recover_ok_t *ok;
                                  ^
    Modules/_librabbitmq/connection.c: At top level:
    Modules/_librabbitmq/connection.c:719:26: warning: ‘PyDict_ToAMQTable’ is static but used in inline function ‘PyDict_to_basic_properties’ which is not static
             props->headers = PyDict_ToAMQTable(conn, value, pool);
                              ^
    Modules/_librabbitmq/connection.c:496:17: warning: ‘AMQTable_toPyDict’ is static but used in inline function ‘basic_properties_to_PyDict’ which is not static
             value = AMQTable_toPyDict(&(props->headers));
                     ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/aron/.virtualenvs/pp/bin/python2 -c "import setuptools, tokenize; __file__='/home/aron/.virtualenvs/pp/src/librabbitmq/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/aron/.virtualenvs/pp/src/librabbitmq
```

The two actual errors in this output are:
```
incompatible type for argument 7 of ‘amqp_exchange_declare’
```
and
```
error: too many arguments to function ‘amqp_exchange_declare’
```

What am I missing here?

**Comment by agriffis** [comment]
Oh there we go. Just needed to remove the system-installed librabbitmq which is old.

**Comment by agriffis** [comment]
This doesn't completely repair installation on Fedora:
1. If you have librabbitmq-devel rpm installed, pip install fails.
2. `pip install .` on local git checkout works, but `pip install -e` from git repo doesn't. The resulting commands are `setup.py install` and `setup.py develop` respectively, and the latter fails on an include file.

But this PR is still a step in the right direction. It seems pointless to remove `-Wall` from `CFLAGS`

**Comment by thedrow** [comment]
@ask Was there a good reason for you to do this?

**Comment by agriffis** [comment]
@ask Just hit this again today on another Fedora machine. Any reason not to pull this?

**Comment by ask** [comment]
Why would removing `-Wall` break compilation? That doesn't make any sense to me, does the compiler enable some other flags in lieu of it?

I removed it because rabbitmq-c has a crazy amount of warnings.

**Comment by agriffis** [comment]
@ask I guess you found the answer in #68 but here it is: `cc1: error: -Wformat-security ignored without -Wformat [-Werror=format-security]` ... so some warning flags depend on others. In this case `-Wall` was standing in for `-Wformat`

**Pull request merged**
